local FLOORS = require "world.balance.def.floor_types"

local M = {}

M = {
	FLOORS.START,
	FLOORS.BASE_STAIRS_180,
	FLOORS.BASE_STAIRS,
	FLOORS.BASE_STAIRS_180,
	FLOORS.BASE_STAIRS,
	FLOORS.BASE_STAIRS_180,
	FLOORS.BASE_STAIRS,
	FLOORS.BASE_STAIRS_180,
	FLOORS.BASE_STAIRS,
	FLOORS.BASE_STAIRS_180,

	FLOORS.BASE_STAIRS_LOCKED, --11
	FLOORS.BASE_NO_FLOOR_180,

	FLOORS.BASE_STAIRS,
	FLOORS.BASE_STAIRS_180,
	FLOORS.BASE_STAIRS,
	FLOORS.BASE_STAIRS_180,
	FLOORS.BASE_STAIRS,
	FLOORS.BASE_STAIRS_180,
	FLOORS.BASE_STAIRS,
	FLOORS.BASE_STAIRS_180,
	FLOORS.BASE_STAIRS,
	FLOORS.BASE_STAIRS_180,
	FLOORS.BASE_STAIRS,
	FLOORS.BASE_STAIRS_180,
	FLOORS.BASE_STAIRS,
	FLOORS.BASE_STAIRS_180,
	FLOORS.BASE_STAIRS,

	FLOORS.BASE_NO_FLOOR_180,
	FLOORS.BASE_NO_FLOOR,
	FLOORS.BASE_NO_FLOOR_180,
	FLOORS.BASE_NO_FLOOR,
	FLOORS.BASE_NO_FLOOR_180,
	FLOORS.BASE_NO_FLOOR,
	FLOORS.BASE_NO_FLOOR_180,
	FLOORS.BASE_NO_FLOOR,
	FLOORS.BASE_NO_FLOOR_180,
	FLOORS.BASE_NO_FLOOR,
	FLOORS.BASE_NO_FLOOR_180,
	FLOORS.BASE_NO_FLOOR_END,

	FLOORS.BASE_STAIRS_180
}

return M